version: "3"
services:
  nginx:
    image: nginx:1.15.2-alpine
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - net-php
    volumes:
      - ./www:/var/www/html:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/dnmp/:rw
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  php:
    build:
      ./php/
    expose:
      - 9000
    networks:
      - net-php
      - net-mysql
      - net-redis
    volumes:
      -  ./www:/var/www/html:rw
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php/:/var/log/dnmp/:rw
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  mysql:
    image: mysql:5.7.20
    hostname: mysql
    ports:
      - 3306:3306
    networks:
      - net-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lnmp
      - MYSQL_USER=lnmp
      - MYSQL_PASSWORD=lnmp

  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    networks:
      - net-redis

networks:
  net-php:
  net-mysql:
  net-redis:

